# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instruction',
            name='pub_date',
        ),
    ]
